name: Release

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Apt install
        run: sudo ./scripts/aptinstall.sh
      - name: Cache Poetry
        uses: actions/cache@v3
        id: cache-poetry
        with:
          path: .venv
          key: poetry-$
          restore-keys: |
            poetry-$
      - name: Install Poetry
        run: POETRY_VIRTUALENVS_IN_PROJECT=1 ./scripts/poetryinstall.sh
      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry build --format wheel
          poetry publish
